mod app;

use crate::types::data::Data;
use tui::{
    backend::{Backend, CrosstermBackend},
    layout::{Alignment, Constraint, Direction, Layout, Rect},
    style::{Color, Style, Modifier},
    symbols,
    text::Span,
    widgets::{
        Axis, Block, Borders, Cell, Chart, Dataset, GraphType, List, ListItem, Paragraph, Row,
        Table, Wrap,
    },
    Frame, Terminal,
};
use crossterm::{
    event::{self, Event, KeyCode, KeyModifiers, DisableMouseCapture, EnableMouseCapture},
    execute,
    terminal::{disable_raw_mode, enable_raw_mode, EnterAlternateScreen, LeaveAlternateScreen},
};
use std::{
    error::Error,
    io,
    time::{Duration, Instant},
};
use app::{App, Screen, Dir, ActiveBlock};

fn render_assignments<B: Backend>(f: &mut Frame<B>, app: &mut App, layout_chunk: Rect) {
    let selected_style = app.get_highlight_style_from_id(ActiveBlock::Assignments);
    let bold = Style::default().fg(Color::White).add_modifier(Modifier::BOLD);
    let header_cells = ["Course", "Name", "Due Date"].iter().map(|h| Cell::from(*h));
    let header = Row::new(header_cells)
        .style(bold)
        .height(1)
        .bottom_margin(1);
    let numrows = app.data.assignments.len();
    let rows = app.data.assignments.iter().map(|a| {
        let date = if let Some(date) = a.date {
            date.format("%A %d").to_string()
        } else {
            "(No due date)".to_string()
        };
        let cells = vec![
            format!("{}", a.course),
            format!("{}", a.name),
            format!("{}", date),
        ];
        Row::new(cells)
        
    });
    let border_style = app.get_border_style_from_id(ActiveBlock::Assignments);
    let table = Table::new(rows)
        .header(header)
        .block(
            Block::default()
                .borders(Borders::ALL)
                .title("Upcoming Assignments")
                .border_style(border_style),
        )
        .highlight_style(selected_style)
        .widths(&[
            Constraint::Ratio(1, 10),
            Constraint::Ratio(6, 10),
            Constraint::Ratio(3, 10),
        ]);
    f.render_stateful_widget(table, layout_chunk, &mut app.assignments_state);
}

fn render_grades<B: Backend>(f: &mut Frame<B>, app: &mut App, layout_chunk: Rect) {
    let selected_style = app.get_highlight_style_from_id(ActiveBlock::Grades);
    let bold = Style::default().fg(Color::White).add_modifier(Modifier::BOLD);
    let header_cells = ["Course", "Grade"].iter().map(|h| Cell::from(*h));
    let header = Row::new(header_cells)
        .style(bold)
        .height(1)
        .bottom_margin(1);
    let rows = app.data.grades.iter().map(|g| {
        let cells = vec![
            format!("{}", g.course),
            format!("{}", g.grade),
        ];
        Row::new(cells)
        
    });
    let border_style = app.get_border_style_from_id(ActiveBlock::Grades);
    let table = Table::new(rows)
        .header(header)
        .block(
            Block::default()
                .borders(Borders::ALL)
                .title("Grades")
                .border_style(border_style),
        )
        .highlight_style(selected_style)
        .widths(&[
            Constraint::Ratio(1, 2),
            Constraint::Ratio(1, 2),
        ]);
    f.render_stateful_widget(table, layout_chunk, &mut app.assignments_state);
}

fn render_welcome<B: Backend>(f: &mut Frame<B>, app: &mut App, layout_chunk: Rect) {
    let welcome = Paragraph::new(format!("\nToday is {}, there are {} upcoming assignments", chrono::Local::now().format("%A %d %B"), app.data.assignments.len()))
        .block(
            Block::default()
                .borders(Borders::ALL)
                .title("Welcome to CanvasTUI")
        )
        .alignment(Alignment::Center)
        .wrap(Wrap { trim: true });
    f.render_widget(welcome, layout_chunk);
}

fn render_plan<B: Backend>(f: &mut Frame<B>, app: &mut App, layout_chunk: Rect) {
    let welcome = Paragraph::new("Place study/work plan generated by groq here.")
        .block(
            Block::default()
                .borders(Borders::ALL)
                .title("Study Plan")
        )
        .alignment(Alignment::Left)
        .wrap(Wrap { trim: true });
    f.render_widget(welcome, layout_chunk);
}

fn render_default<B: Backend>(f: &mut Frame<B>, app: &mut App) {
    let chunks = Layout::default()
        .direction(Direction::Horizontal)
        .constraints([Constraint::Ratio(2, 3), Constraint::Ratio(1, 3)].as_ref())
        .split(f.size());

    let left_chunks = Layout::default()
        .direction(Direction::Vertical)
        .constraints([Constraint::Ratio(1, 10), Constraint::Ratio(9, 20)].as_ref())
        .split(chunks[0]);

    let right_chunks = Layout::default()
        .direction(Direction::Vertical)
        .constraints([Constraint::Ratio(3, 10), Constraint::Ratio(7, 10)].as_ref())
        .split(chunks[1]);

    render_welcome(f, app, left_chunks[0]);
    render_assignments(f, app, left_chunks[1]);
    render_grades(f, app, right_chunks[0]);
    render_plan(f, app, right_chunks[1]);
}


pub fn run(data: Data) -> Result<(), Box<dyn Error>>{
    // setup terminal
    enable_raw_mode()?;
    let mut stdout = io::stdout();
    execute!(stdout, EnterAlternateScreen, EnableMouseCapture)?;
    let backend = CrosstermBackend::new(stdout);
    let mut terminal = Terminal::new(backend)?;

    // create app and run it
    let mut app = App::new(data, Duration::from_millis(1000));

    // Main loop and tick logic
    let mut last_tick = Instant::now();
    loop {
        terminal.draw(|f| match app.route.screen {
            Screen::Default => render_default(f, &mut app),
            Screen::Help => todo!("Help screen not implemented"),
        })?;

        // Non-blocking key detection
        let timeout = app
            .tick_rate
            .checked_sub(last_tick.elapsed())
            .unwrap_or(Duration::from_secs(0));
        if event::poll(timeout)? {
            if handle_input(&mut app)? {
                break;
            }
        }
        if last_tick.elapsed() >= app.tick_rate {
            app.on_tick();
            last_tick = Instant::now();
        }
    }


    // restore terminal
    disable_raw_mode()?;
    execute!(
        terminal.backend_mut(),
        LeaveAlternateScreen,
        DisableMouseCapture
    )?;
    terminal.show_cursor()?;

    Ok(())
}

fn handle_input(app: &mut App) -> Result<bool, Box<dyn Error>> {
    if let Event::Key(key) = event::read()? {
        match key.modifiers {
            KeyModifiers::NONE => match key.code {
                KeyCode::Esc => app.esc(),
                KeyCode::Enter => app.enter(),
                KeyCode::Char('h') => app.mv(Dir::Left),
                KeyCode::Char('j') => app.mv(Dir::Down),
                KeyCode::Char('k') => app.mv(Dir::Up),
                KeyCode::Char('l') => app.mv(Dir::Right),
                KeyCode::Char('q') => return Ok(true),
                _ => (),
            },
            KeyModifiers::CONTROL => match key.code {
                KeyCode::Char('c') => app.esc(),
                _ => (),
            },
            _ => (),
        }
    }
    Ok(false)
}

